#### 1. 넘파이 ndarray 개요

In [1]:
import numpy as np

In [6]:
## 1차원 ndarray
array1 = np.array([1,2,3])
print('array1 type : ',type(array1))
print('array1 array 형태 : ',array1.shape)

## 2차원 ndarray
array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type : ',type(array2))
print('array2 array 형태 : ',array2.shape)

## array1과 동일한 데이터 갯수이지만 2차원 ndarray
array3 = np.array([[1,2,3]])
print('array3 type : ',type(array3))
print('array3 array 형태 : ',array3.shape)

## 메쏘드 ndim으로 차원확인 가능
print(f'array1 : {array1.ndim}차원, array2 : {array2.ndim}차원, array3 : {array3.ndim}차원')

array1 type :  <class 'numpy.ndarray'>
array1 array 형태 :  (3,)
array2 type :  <class 'numpy.ndarray'>
array2 array 형태 :  (2, 3)
array3 type :  <class 'numpy.ndarray'>
array3 array 형태 :  (1, 3)
array1 : 1차원, array2 : 2차원, array3 : 2차원


#### 2. ndarray 데이터타입

In [10]:
# list1의 데이터타입은 type으로, 리스트 내 원소의 데이터 타입은 dtype 속성으로 확인
list1 = [1,2,3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [13]:
# 리스트는 여러개의 데이터 타입이 동시에 존재 가능
# 하지만 ndarray는 하나의 데이터 타입만 존재해야 하므로 자동적으로 형변환

## 정수 / 문자 혼용은 문자데이터로
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

## 정수 / 실수 혼용은 실수데이터로
list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [18]:
# astype() 메서드로 명시적 형변환 가능

## 정수 -> 실수
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

## 실수 -> 정수
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

## 실수 -> 정수 변환 시 소숫점은 버림
array_float1 = np.array([1.1,3.3,6.6])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 3 6] int32


#### 3. ndarray를 편리하게 생성하기 - arange, zeros, ones

In [25]:
# arange() : 파이썬의 range와 유사
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

## start와 stop값 지정도 가능
sequence_array2 = np.arange(3,15)
print(sequence_array2)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)
[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [26]:
# zeros() : 튜플로 shape값 입력 시 모든 값이 0으로 채워진 ndarray반환
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [29]:
# ones() : zeros와 동일한데 모든 값이 1로 채워진 ndarray반환
ones_array = np.ones((3,2))
print(ones_array)
print(ones_array.dtype, ones_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


#### 4. ndarray의 차원과 크기를 변경하기 - reshape()

In [31]:
array1 = np.arange(10)
print('array1 :\n', array1)

## array1을 2행 5열 ndarray로 변환
array2 = array1.reshape(2,5)
print('array2 :\n', array2)

## array1을 5행 2열로 변환
array3 = array1.reshape(5,2)
print('array3 :\n', array3)

## 지정된 사이즈로 변경이 불가능하면 오류발생
# array4 = array1.reshape(4,3)
# print('array4 :\n', array4)

array1 :
 [0 1 2 3 4 5 6 7 8 9]
array2 :
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 :
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [35]:
# -1 인자를 활용하면 알아서 맞춰서 만들어줌
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)

array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [39]:
# -1 인자를 이용하여 반드시 1개의 칼럼을 가진 ndarray로 만들때 주로 사용
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d :\n', array3d)

## 3차원 ndarray를 2차원 ndarray로 반환
array5 = array3d.reshape((-1,1))
print('array5 :\n', array5)

## 1차원 ndarray를 2차원 ndarray로 반환
array6 = array1.reshape((-1,1))
print('array6 :\n', array6)

array3d :
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
array5 :
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
array6 :
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


#### 5. 넘파이의 ndarray의 데이터 세트 선택하기 : 인덱싱