### 1. 넘파이 ndarray 개요

In [1]:
import numpy as np

In [2]:
## 1차원 ndarray
array1 = np.array([1,2,3])
print('array1 type : ',type(array1))
print('array1 array 형태 : ',array1.shape)

## 2차원 ndarray
array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type : ',type(array2))
print('array2 array 형태 : ',array2.shape)

## array1과 동일한 데이터 갯수이지만 2차원 ndarray
array3 = np.array([[1,2,3]])
print('array3 type : ',type(array3))
print('array3 array 형태 : ',array3.shape)

## 메쏘드 ndim으로 차원확인 가능
print(f'array1 : {array1.ndim}차원, array2 : {array2.ndim}차원, array3 : {array3.ndim}차원')

array1 type :  <class 'numpy.ndarray'>
array1 array 형태 :  (3,)
array2 type :  <class 'numpy.ndarray'>
array2 array 형태 :  (2, 3)
array3 type :  <class 'numpy.ndarray'>
array3 array 형태 :  (1, 3)
array1 : 1차원, array2 : 2차원, array3 : 2차원


### 2. ndarray 데이터타입

In [3]:
# list1의 데이터타입은 type으로, 리스트 내 원소의 데이터 타입은 dtype 속성으로 확인
list1 = [1,2,3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [4]:
# 리스트는 여러개의 데이터 타입이 동시에 존재 가능
# 하지만 ndarray는 하나의 데이터 타입만 존재해야 하므로 자동적으로 형변환

## 정수 / 문자 혼용은 문자데이터로
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

## 정수 / 실수 혼용은 실수데이터로
list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [5]:
# astype() 메서드로 명시적 형변환 가능

## 정수 -> 실수
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

## 실수 -> 정수
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

## 실수 -> 정수 변환 시 소숫점은 버림
array_float1 = np.array([1.1,3.3,6.6])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 3 6] int32


### 3. ndarray를 편리하게 생성하기 - arange, zeros, ones

In [6]:
# arange() : 파이썬의 range와 유사
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

## start와 stop값 지정도 가능
sequence_array2 = np.arange(3,15)
print(sequence_array2)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)
[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [7]:
# zeros() : 튜플로 shape값 입력 시 모든 값이 0으로 채워진 ndarray반환
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [8]:
# ones() : zeros와 동일한데 모든 값이 1로 채워진 ndarray반환
ones_array = np.ones((3,2))
print(ones_array)
print(ones_array.dtype, ones_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### 4. ndarray의 차원과 크기를 변경하기 - reshape()

In [9]:
array1 = np.arange(10)
print('array1 :\n', array1)

## array1을 2행 5열 ndarray로 변환
array2 = array1.reshape(2,5)
print('array2 :\n', array2)

## array1을 5행 2열로 변환
array3 = array1.reshape(5,2)
print('array3 :\n', array3)

## 지정된 사이즈로 변경이 불가능하면 오류발생
# array4 = array1.reshape(4,3)
# print('array4 :\n', array4)

array1 :
 [0 1 2 3 4 5 6 7 8 9]
array2 :
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 :
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [10]:
# -1 인자를 활용하면 알아서 맞춰서 만들어줌
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)

array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [11]:
# -1 인자를 이용하여 반드시 1개의 칼럼을 가진 ndarray로 만들때 주로 사용
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d :\n', array3d)

## 3차원 ndarray를 2차원 ndarray로 반환
array5 = array3d.reshape((-1,1))
print('array5 :\n', array5)

## 1차원 ndarray를 2차원 ndarray로 반환
array6 = array1.reshape((-1,1))
print('array6 :\n', array6)

array3d :
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
array5 :
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
array6 :
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


### 5. 넘파이의 ndarray의 데이터 세트 선택하기 : 인덱싱

#### 5.1 단일값 추출

In [12]:
## 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start = 1, stop = 10)
print(array1)

## index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:',value)
print(type(value))

## 원소로 음수를 넣으면 뒤에서부터 순서대로 단일값 추출가능
print('맨 뒤의 값 :',array1[-1], '맨 뒤에서 두번째 값 :', array1[-2])

[1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>
맨 뒤의 값 : 9 맨 뒤에서 두번째 값 : 8


In [13]:
# 단일 인덱스를 이용하여 ndarray값 수정하기
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [14]:
# 다차원 ndarray에서 단일값 추출하기

array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3,3)
print(array2d)

for i in range(3):
    for j in range(3):
        print(f"(row={i}, col={j}) index가 가리키는 값 : ", array2d[i,j])
        
## ndarray에서는 행렬 대신 axis=0 (=row) / axis=1 (=col) 이라고 표현

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index가 가리키는 값 :  1
(row=0, col=1) index가 가리키는 값 :  2
(row=0, col=2) index가 가리키는 값 :  3
(row=1, col=0) index가 가리키는 값 :  4
(row=1, col=1) index가 가리키는 값 :  5
(row=1, col=2) index가 가리키는 값 :  6
(row=2, col=0) index가 가리키는 값 :  7
(row=2, col=1) index가 가리키는 값 :  8
(row=2, col=2) index가 가리키는 값 :  9


#### 5.2 슬라이싱

In [15]:
# 슬라이싱 : ':'기호를 사용하여 연속한 여러개의 데이터를 추출하는 방법

array1 = np.arange(start=1, stop=10)
array3 = array1[:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [16]:
# 슬라이싱에서 ':'기호 앞뒤 원소를 비워두면 처음부터 or 끝까지를 의미
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [17]:
# 다차원 ndarray에서 슬라이싱하기

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2,0:2] \n', array2d[0:2,0:2])
print('array2d[1:3,0:3] \n', array2d[1:3,0:3])
print('array2d[1:3,:] \n', array2d[1:3,:])
print('array2d[:,:] \n', array2d[:,:])
print('array2d[:2,1:] \n', array2d[:2,1:])

## 한쪽에는 슬라이싱, 한쪽에는 단일값 인덱싱도 가능
print('array2d[:2,0] \n', array2d[:2,0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2] 
 [[1 2]
 [4 5]]
array2d[1:3,0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:] 
 [[4 5 6]
 [7 8 9]]
array2d[:,:] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:] 
 [[2 3]
 [5 6]]
array2d[:2,0] 
 [1 4]


#### 5.3 팬시 인덱싱

In [18]:
# 팬시 인덱싱 : 리스트를 이용하여 원하는 행렬을 지정하여 ndarray를 반환하는 방식

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3) 

array3 = array2d[[0,2],1]
print('array2d[[0,2],1] => ', array3)

array4 = array2d[[0,1],0:2]
print('array2d[[0,1],0:2] => ', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ', array5.tolist())

array2d[[0,2],1] =>  [2 8]
array2d[[0,1],0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


#### 5.4 불린 인덱싱

In [19]:
# 불린 인덱싱 : ndarray에 조건을 걸거나 검색을 하여 원하는 정보만 추출하는 방식

array1d = np.arange(start=1, stop=10)

array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


### 6. 행렬의 정렬

In [26]:
org_array = np.array([3,1,9,5])
print('원본 행렬 : ', org_array)

## np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬 : ', sort_array1)
print('np.sort() 호출 후 원본 행렬 : ', org_array)
## 원본 행렬은 그대로, 정렬된 행렬을 반환

## ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬 : ', sort_array2)
print('org_array.sort() 호출 후 원본 행렬 : ', org_array)
## 원본행렬을 정렬하고 None을 반환

원본 행렬 :  [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬 :  [1 3 5 9]
np.sort() 호출 후 원본 행렬 :  [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬 :  None
org_array.sort() 호출 후 원본 행렬 :  [1 3 5 9]


In [28]:
# 내림차순으로 정렬 : [::-1]
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬 : ',sort_array1_desc)

내림차순으로 정렬 :  [9 5 3 1]


In [30]:
# 다차원 행렬일 경우 axis별로 정렬 가능

array2d = np.array([[8,12],
                    [7,1 ]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [35]:
# np.argsort() : 정렬된 행렬의 원본 행렬 인덱스를 ndarray형태로 반환

org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스 : ',sort_indices)
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스 : ',sort_indices[::-1])

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스 :  [1 0 3 2]
행렬 내림차순 정렬 시 원본 행렬의 인덱스 :  [2 3 0 1]


In [38]:
# 넘파이는 메타 데이터를 가지고 있지 않기 때문에 argsort()로 데이터 추출

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

## argsort() 메서드로 인덱스를 뽑아 팬시인덱싱 적용 
sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스 : ', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력 : ', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스 :  [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력 :  ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 7. 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

In [41]:
# 행렬 내적(행렬 곱)

A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7 ,8 ],
              [9 ,10],
              [11,12]])

dot_product = np.dot(A,B)
print('행렬 내적 결과 :\n', dot_product)

행렬 내적 결과 :
 [[ 58  64]
 [139 154]]


In [46]:
# 전치 행렬

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬 : \n', transpose_mat)

A의 전치 행렬 : 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


AttributeError: 'numpy.ndarray' object has no attribute 't'