### 1. 사이킷런의 주요모듈

|분류|모듈명|설명|
|:------|:---|:---|
|예제 데이터|sklearn.datasets|사이킷 런에 내장된 예제 데이터 셋|
|피처 처리|sklearn.preprocessing|데이터 전처리에 필요한 다양한 가공 기능 제공|
||sklearn.feature_selection|알고리즘에 큰 영향을 미치는 피처를 우선순위로 셀렉션하는 다양한 기능 제공|
||sklearn.feature_extraction|텍스트/이미지 데이터의 벡터화된 피처를 추출|
|피처처리/차원축소|sklearn.decomposition|차원 축소와 관련한 알고리즘 지원|
|데이터분리,검증,파라미터튜닝|sklearn.model_selection|교차검증을 위한 데이터분리, 최적 파라미터 추출|
|평가|sklearn.metrics|accuracy, precision, recall등 다양한 성능 측정 방법 제공|
|머신러닝 알고리즘|sklearn.ensemble|랜덤포레스트, 에이다 부스트 등 앙상블 알고리즘 제공|
||sklearn.linear_model|선형회귀, 릿지, 라쏘 등 회귀관련 알고리즘 제공|
||sklearn.naive_bayes|나이브베이즈 알고리즘 제공|
||sklearn.neighbors|최근접 이웃 알고리즘 제공|
||sklearn.svm|서포트 벡터 머신 알고리즘 제공|
||sklearn.tree|의사결정트리 알고리즘 제공|
||sklearn.cluster|비지도 클러스터링 알고리즘 제공|
|유틸리티|sklearn.pipeline|변환과 학습, 예측등을 함께 묶어 실행할 수 있는 유틸리티 제공|

### 2. 내장된 예제 데이터 세트

|API명|설명|
|:------|:---|
|datasets.load_breast_cancer()|분류, 위스콘신 유방암 피처들과 악/음성 레이블 데이터 세트|
|datasets.load_digits()|분류, 0에서 9까지 숫자의 이미지 픽셀 데이터 세트|
|datasets.load_iris()|분류, 붓꽃에 대한 피처를 가진 데이터 세트|
|datasets.load_boston()|회귀, 보스턴의 집 피처들과 가격에 대한 데이터 세트|
|datasets.load_diabetes()|회귀, 당뇨데이터 세트|

fetch계열의 명령은 데이터세트의 크기가 커서 인터넷에서 내려받아 서브디렉토리에 저장한 후 추후 불러옴 

|API명|설명|
|:------|:---|
|fetch_covtype()|토지 조사 자료|
|fetch_20newsgroups()|뉴스그룹 텍스트 자료|
|fetch_olivetti_faces()|얼굴 이미지 자료|
|fetch_lfw_people()|얼굴 이미지 자료|
|fetch_lfw_pairs()|얼굴 이미지 자료|
|fetch_rcv1()|로이터 뉴스 말뭉치|
|fetch_mldata()|ML 웹사이트에서 다운로드|

대표적인 표본생성기

|API명|설명|
|:------|:---|
|datasets.make_classifications()|분류를 위한 데이터 세트 생성|
|datasets.make_blobs()|클러스터링을 위한 데이터 세트 생성|



    ** 대다수의 데이터세트가 딕셔너리의 형태로 구성
        Key값 - 1) data : 피처의 데이터 세트
                2) target : 분류일때는 레이블 값, 회귀일때는 숫자 결괏값 데이터 세트
                3) target_names : 개별 레이블의 이름
                4) feature_names : 피처의 이름
                5) DESCR : 데이터 세트에 대한 설명과 피처의 설명

In [1]:
# 붓꽃 데이터 세트 생성
from sklearn.datasets import load_iris

iris_data = load_iris()
print(type(iris_data))

<class 'sklearn.utils.Bunch'>


In [3]:
# 딕셔너리 형태(Bunch 클래스)인 붓꽃 데이터의 key값 확인
keys = iris_data.keys()
print('붓꽃 데이터 세트의 키들 : ', keys)

붓꽃 데이터 세트의 키들 :  dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [5]:
# Key들이 가리키는 값 확인

print('feature_names의 type:', type(iris_data.feature_names))
print('feature_names의 shape:', len(iris_data.feature_names))
print(iris_data.feature_names)

print('\n target_names의 type:', type(iris_data.target_names))
print('target_names의 shape:', len(iris_data.target_names))
print(iris_data.target_names)

print('\n data의 type:', type(iris_data.data))
print('data의 shape:', iris_data.data.shape)
print(iris_data['data'])

print('\n target의 type:', type(iris_data.target))
print('target의 shape:', iris_data.target.shape)
print(iris_data.target)

feature_names의 type: <class 'list'>
feature_names의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names의 type: <class 'numpy.ndarray'>
target_names의 shape: 3
['setosa' 'versicolor' 'virginica']

 data의 type: <class 'numpy.ndarray'>
data의 shape: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.