### 1. 데이터 인코딩

#### 1.1 레이블 인코딩
    카테고리 피처를 코드형 숫자값으로 변환
      ex) TV / 컴퓨터 / 에어컨  -> 1:TV / 2:컴퓨터 / 3:에어컨
    
    카테고리가 정수형으로 표현되면서 ML알고리즘이 명목변수를 비율변수로 착각하게 만드는 단점 존재
      -> Tree 계열 ML 알고리즘에서는 무관하지만 회귀 계열 ML 알고리즘에서는 레이블 인코딩을 사용하면 안됨

In [3]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기','선풍기', '믹서', '믹서']

# LabelEncoder를 객체로 생성한 후, fit()과 trainsform()으로 레이블 인코딩 수행
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값 :',labels)

인코딩 변환값 : [0 1 4 5 3 3 2 2]


In [5]:
# LabelEncoder 객체의 classes_속성값으로 인코딩 클래스 확인
print('인코딩 클래스 :', encoder.classes_)

인코딩 클래스 : ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [7]:
# inverse_transform() 메서드로 디코딩 가능
print('디코딩 원본값: ', encoder.inverse_transform(labels))

디코딩 원본값:  ['TV' '냉장고' '전자레인지' '컴퓨터' '선풍기' '선풍기' '믹서' '믹서']


#### 1.2 원-핫 인코딩
    카테고리 피처의 클래스를 하나의 칼럼으로 만듬

In [12]:
# OneHotEncoder 클래스로 원-핫 인코딩 수행
# 단 LabelEncoder와 달리
#    1) 변환하기 전 모든 문자열 값이 숫자형으로 변환되어야 함
#    2) 입력값으로 2차원 데이터가 필요

from sklearn.preprocessing import OneHotEncoder, LabelEncoder
import numpy as np

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기','선풍기', '믹서', '믹서']

## 먼저 LabelEncoder를 이용 숫자값으로 변환
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
## 2차원 데이터로 변환
labels = labels.reshape(-1,1)

# One-Hot Encoding 수행
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


In [13]:
# 판다스에서는 OneHotEncoding을 지원하는 API get_dummies()가 있음 (숫자형 변환 안해도 알아서 해줌)

import pandas as pd
df = pd.DataFrame({'item' : ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기','선풍기', '믹서', '믹서']})
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

### 2. 피처스케일링과 정규화

#### 2.1 표준화 : StandardScaler

    표준화는 피처를 평균 = 0, 분산 = 1인 가우시안 정규분포를 가진 값으로 변환하는 기술
    데이터가 가우시안 분포를 가지고 있다고 가정하는 ML 알고리즘 이용시 필수적으로 표준화해야함
      ex) 서포트 벡터 머신 / 선형회귀 / 로지스틕 회귀 등

In [17]:
from sklearn.datasets import load_iris
import pandas as pd
# 붓꽃 데이터 세트를 로딩하고 dfm으로 반환

iris = load_iris()
iris_df = pd.DataFrame(data = iris.data, columns = iris.feature_names)

print('feature들의 평균 값')
print(iris_df.mean())
print('\nfeature 들의 분산 값')
print(iris_df.var())

feature들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature 들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [23]:
# StandardScaler로 표준화
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

## transform()을 하면 ndarray가 반환되므로 dfm으로 변환해야함
iris_df_scaled = pd.DataFrame(iris_scaled, columns=iris.feature_names)
print('feature들의 평균 값')
print(iris_df_scaled.mean())
print('\nfeature들의 분산 값')
print(iris_df_scaled.var())

feature들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


#### 2.2 정규화 : MinMaxSclaer
    정규화는 피처를 0~1 사이의 값으로 변환하는 기술
    주로 각 피처의 측정단위가 다를때 개별 데이터의 크기를 모두 똑같은 단위로 변경하기 위해 사용(cm vs m^2)
    데이터가 가우시안 분포를 따르지 않을때 주로 사용

In [37]:
# MinMaxScaler로 정규화

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

## transform()을 하면 ndarray가 반환되므로 dfm으로 변환 필요
iris_df_scaled = pd.DataFrame(data = iris_scaled, columns = iris.feature_names)
print('feature들의 최솟값')
print(iris_df_scaled.min())
print('feature들의 최댓값')
print(iris_df_scaled.max())

feature들의 최솟값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
feature들의 최댓값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


### 3. 학습데이터와 테스트 데이터의 스케일링 변환 시 유의점
     학습데이터에만 fit() 적용할 것!
     
     우선 전체 데이터에 MinMaxScaler를 적용하고 train_test_split() 하는것이 바람직

In [40]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

## 학습데이터는 0~10 까지, 테스트데이터는 0~5까지
train_array = np.arange(0,11).reshape(-1,1)
test_array = np.arange(0,6).reshape(-1,1)

In [45]:
scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)

print('원본 train_array 데이터 :', train_array.reshape(-1))
print('Scale된 train_array 데이터 :', train_scaled.reshape(-1))

원본 train_array 데이터 : [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array 데이터 : [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [46]:
## 이때 테스트 데이터에도 fit을 해버리면 scaling의 의미가 사라짐
scaler.fit(test_array)
test_scaled = scaler.transform(test_array)

print('원본 test_array 데이터 :', test_array.reshape(-1))
print('Scale된 test_array 데이터 :', test_scaled.reshape(-1))

원본 test_array 데이터 : [0 1 2 3 4 5]
Scale된 test_array 데이터 : [0.  0.2 0.4 0.6 0.8 1. ]


In [47]:
## 테스트 데이터에는 transform만 할 것
scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)
test_scaled = scaler.transform(test_array)

print('원본 test_array 데이터 :', test_array.reshape(-1))
print('Scale된 test_array 데이터 :', test_scaled.reshape(-1))

원본 test_array 데이터 : [0 1 2 3 4 5]
Scale된 test_array 데이터 : [0.  0.1 0.2 0.3 0.4 0.5]
